services:
  upload-pinata:
    build: ./upload
    environment:
      PINATA_JWT: ${PINATA_JWT:-null}
      DATA: ${DATA-unigecard}
      PINATA_URL: ${PINATA_URL:-null}
    volumes:
      - ./unigecard:/app/unigecard

  upload-pinata-test:
    build: ./upload
    environment:
      PINATA_JWT: ${PINATA_JWT:-null}
      DATA: ${DATA-pokemon}
      PINATA_URL: ${PINATA_URL:-null}
    volumes:
      - ./pokemon:/app/pokemon

  frontend:
    build:
      context: ./infUnigeNFT
    volumes:
      - ./infUnigeNFT:/app
    network_mode: host