name: Build & Deploy Nuxt site

on:
  push:
    paths:
      - "infUnigeNFT/**"
  workflow_dispatch:

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 20
          cache: npm

      - name: Install dependencies in root (if needed)
        run: npm ci || true

      - name: Install dependencies in Nuxt app
        working-directory: infUnigeNFT
        run: npm ci

      - name: Patch baseURL for GitHub Pages
        working-directory: infUnigeNFT
        run: |
          sed -i 's|baseURL: .*$|baseURL: "/NFT-Unigecard/",|' nuxt.config.ts

      - name: Generate static site
        working-directory: infUnigeNFT
        run: npx nuxi generate

      - name: Copy generated files to dist
        run: |
          rm -rf dist
          cp -r infUnigeNFT/.output/public dist

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./dist
          publish_branch: gh-pages
